[2024-04-15T23:50:08.863+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T23:50:09.087+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: m_dag_ejecutar.ejecutar_script_python manual__2024-04-15T23:50:04.861858+00:00 [queued]>
[2024-04-15T23:50:09.154+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: m_dag_ejecutar.ejecutar_script_python manual__2024-04-15T23:50:04.861858+00:00 [queued]>
[2024-04-15T23:50:09.155+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-15T23:50:09.345+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ejecutar_script_python> on 2024-04-15 23:50:04.861858+00:00
[2024-04-15T23:50:09.362+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=331) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T23:50:09.372+0000] {standard_task_runner.py:63} INFO - Started process 332 to run task
[2024-04-15T23:50:09.380+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'm_dag_ejecutar', 'ejecutar_script_python', 'manual__2024-04-15T23:50:04.861858+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/Scraping.py', '--cfg-path', '/tmp/tmpxubyjt3c']
[2024-04-15T23:50:09.395+0000] {standard_task_runner.py:91} INFO - Job 249: Subtask ejecutar_script_python
[2024-04-15T23:50:09.550+0000] {task_command.py:426} INFO - Running <TaskInstance: m_dag_ejecutar.ejecutar_script_python manual__2024-04-15T23:50:04.861858+00:00 [running]> on host b67ce4676396
[2024-04-15T23:50:09.728+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='usuario' AIRFLOW_CTX_DAG_ID='m_dag_ejecutar' AIRFLOW_CTX_TASK_ID='ejecutar_script_python' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T23:50:04.861858+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T23:50:04.861858+00:00'
[2024-04-15T23:50:09.730+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T23:50:09.881+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2024-04-15T23:50:09.882+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-15T23:50:09.892+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T23:50:09.966+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=m_dag_ejecutar, task_id=ejecutar_script_python, execution_date=20240415T235004, start_date=20240415T235009, end_date=20240415T235009
[2024-04-15T23:50:10.165+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T23:50:10.232+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T23:50:10.241+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
