[2024-04-07T14:43:13.793+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_clima.ejecutar_mi_script_task scheduled__2024-04-06T00:00:00+00:00 [queued]>
[2024-04-07T14:43:13.807+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_clima.ejecutar_mi_script_task scheduled__2024-04-06T00:00:00+00:00 [queued]>
[2024-04-07T14:43:13.808+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-07T14:43:13.829+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): ejecutar_mi_script_task> on 2024-04-06 00:00:00+00:00
[2024-04-07T14:43:13.835+0000] {standard_task_runner.py:60} INFO - Started process 142 to run task
[2024-04-07T14:43:13.840+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_clima', 'ejecutar_mi_script_task', 'scheduled__2024-04-06T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/Dag_clima.py', '--cfg-path', '/tmp/tmpmanz18de']
[2024-04-07T14:43:13.845+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask ejecutar_mi_script_task
[2024-04-07T14:43:13.933+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_clima.ejecutar_mi_script_task scheduled__2024-04-06T00:00:00+00:00 [running]> on host 0ebc2d070f55
[2024-04-07T14:43:14.044+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_clima' AIRFLOW_CTX_TASK_ID='ejecutar_mi_script_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-06T00:00:00+00:00'
[2024-04-07T14:43:14.048+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-07T14:43:14.050+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python "C:\\Users\\gusta\\Desktop\\Data Engineer\\Semana 7 - Dataframes con SQLalchemy y Psycopg\\TP Entregable\\Script.py"']
[2024-04-07T14:43:14.070+0000] {subprocess.py:86} INFO - Output:
[2024-04-07T14:43:14.141+0000] {subprocess.py:93} INFO - python: can't open file 'C:\Users\gusta\Desktop\Data Engineer\Semana 7 - Dataframes con SQLalchemy y Psycopg\TP Entregable\Script.py': [Errno 2] No such file or directory
[2024-04-07T14:43:14.147+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-07T14:43:14.169+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-07T14:43:14.182+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_clima, task_id=ejecutar_mi_script_task, execution_date=20240406T000000, start_date=20240407T144313, end_date=20240407T144314
[2024-04-07T14:43:14.216+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 60 for task ejecutar_mi_script_task (Bash command failed. The command returned a non-zero exit code 2.; 142)
[2024-04-07T14:43:14.254+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-07T14:43:14.289+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
