[2024-04-17T00:03:07.986+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:03:08.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:03:08.042+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:03:08.037+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:03:08.513+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:03:08.416+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:03:08.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:03:13.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 5.830 seconds
[2024-04-17T00:03:45.772+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:03:45.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:03:45.962+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:03:45.957+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:03:47.510+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:03:46.880+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:03:47.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:03:47.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 2.208 seconds
[2024-04-17T00:04:20.353+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:04:20.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:04:20.431+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:04:20.431+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:04:21.755+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:04:21.400+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:04:21.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:04:22.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 1.975 seconds
[2024-04-17T00:04:54.397+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:04:54.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:04:54.410+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:04:54.409+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:04:55.728+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:04:55.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:04:55.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:05:10.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 15.629 seconds
[2024-04-17T00:05:40.710+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:05:40.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:05:40.716+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:05:40.715+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:05:40.784+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:05:40.752+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:05:40.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:05:41.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.889 seconds
[2024-04-17T00:06:17.553+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:06:17.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:06:17.574+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:06:17.573+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:06:17.720+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:06:17.680+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:06:17.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:06:28.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 10.671 seconds
[2024-04-17T00:06:58.987+0000] {processor.py:161} INFO - Started process (PID=133) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:06:59.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:06:59.019+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:06:59.018+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:06:59.322+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:06:59.275+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:06:59.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:07:01.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 3.034 seconds
[2024-04-17T00:07:32.722+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:07:32.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:07:32.735+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:07:32.735+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:07:33.049+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:07:32.986+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:07:33.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:07:33.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.643 seconds
[2024-04-17T00:08:04.141+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:08:04.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:08:04.145+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:08:04.145+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:08:04.192+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:08:04.174+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:08:04.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:08:09.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 5.578 seconds
[2024-04-17T00:08:40.082+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:08:40.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:08:40.087+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:08:40.086+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:08:41.321+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:08:41.161+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:08:41.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:08:41.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 1.311 seconds
[2024-04-17T00:09:11.927+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:09:11.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:09:11.945+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:11.944+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:09:12.071+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:12.049+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:09:12.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:09:12.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.268 seconds
[2024-04-17T00:09:43.299+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:09:43.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:09:43.322+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:43.321+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:09:43.400+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:09:43.378+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:09:43.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:09:44.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 1.014 seconds
[2024-04-17T00:10:34.945+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:10:34.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:10:34.996+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:10:34.995+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:10:35.287+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:10:35.248+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:10:35.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:10:35.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.572 seconds
[2024-04-17T00:11:05.673+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:11:05.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:11:05.842+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:05.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:11:05.892+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:05.874+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:11:05.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:11:07.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 1.648 seconds
[2024-04-17T00:11:38.365+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:11:38.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:11:38.461+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:38.461+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:11:39.281+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:11:39.174+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:11:39.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:11:41.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 3.369 seconds
[2024-04-17T00:12:12.931+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:12:12.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:12:12.960+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:12.959+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:12:13.340+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:13.274+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:12:13.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:12:14.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 1.129 seconds
[2024-04-17T00:12:45.062+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:12:45.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:12:45.072+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:45.071+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:12:45.136+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:12:45.114+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:12:45.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:12:45.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.873 seconds
[2024-04-17T00:13:16.407+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:13:16.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:13:16.412+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:16.412+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:13:16.476+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:16.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:13:16.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:13:16.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.157 seconds
[2024-04-17T00:13:46.922+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:13:46.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:13:46.927+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:46.927+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:13:46.976+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:13:46.959+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:13:46.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:13:47.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.534 seconds
[2024-04-17T00:14:17.608+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:14:17.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:14:17.613+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:17.613+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:14:17.652+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:17.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:14:17.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:14:17.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.093 seconds
[2024-04-17T00:14:47.780+0000] {processor.py:161} INFO - Started process (PID=299) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:14:47.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:14:47.785+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:47.784+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:14:47.833+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:14:47.817+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:14:47.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:14:47.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.111 seconds
[2024-04-17T00:15:18.299+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:15:18.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:15:18.304+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:18.304+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:15:18.360+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:18.341+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:15:18.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:15:18.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.128 seconds
[2024-04-17T00:15:49.177+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:15:49.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:15:49.183+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:49.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:15:49.232+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:15:49.216+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:15:49.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:15:50.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.857 seconds
[2024-04-17T00:16:20.353+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:16:20.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:16:20.359+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:20.358+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:16:20.395+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:20.385+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:16:20.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:16:20.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.093 seconds
[2024-04-17T00:16:51.380+0000] {processor.py:161} INFO - Started process (PID=343) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:16:51.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:16:51.387+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:51.386+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:16:51.462+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:16:51.430+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:16:51.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:16:52.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.880 seconds
[2024-04-17T00:17:22.795+0000] {processor.py:161} INFO - Started process (PID=353) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:17:22.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:17:22.800+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:22.799+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:17:22.843+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:22.830+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:17:22.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:17:23.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.799 seconds
[2024-04-17T00:17:53.799+0000] {processor.py:161} INFO - Started process (PID=364) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:17:53.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:17:53.816+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:53.816+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:17:54.069+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:17:53.928+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:17:54.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:17:54.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.486 seconds
[2024-04-17T00:18:24.579+0000] {processor.py:161} INFO - Started process (PID=375) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:18:24.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:18:24.587+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:24.586+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:18:24.640+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:24.627+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:18:24.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:18:24.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.114 seconds
[2024-04-17T00:18:54.806+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:18:54.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:18:54.811+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:54.810+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:18:54.849+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:18:54.837+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:18:54.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:18:55.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.258 seconds
[2024-04-17T00:19:25.145+0000] {processor.py:161} INFO - Started process (PID=397) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:19:25.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:19:25.148+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:19:25.148+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:19:25.188+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:19:25.176+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:19:25.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:19:25.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.643 seconds
[2024-04-17T00:19:56.821+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:19:56.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:19:56.825+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:19:56.824+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:19:56.863+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:19:56.850+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:19:56.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:19:56.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.086 seconds
[2024-04-17T00:20:27.415+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:20:27.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:20:27.424+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:27.423+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:20:27.534+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:27.486+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:20:27.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:20:27.913+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.516 seconds
[2024-04-17T00:20:58.987+0000] {processor.py:161} INFO - Started process (PID=431) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:20:58.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:20:59.002+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:59.001+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:20:59.109+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:20:59.064+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:20:59.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:20:59.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.551 seconds
[2024-04-17T00:21:30.378+0000] {processor.py:161} INFO - Started process (PID=443) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:21:30.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:21:30.383+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:21:30.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:21:30.447+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:21:30.431+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:21:30.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:21:34.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 3.948 seconds
[2024-04-17T00:22:11.402+0000] {processor.py:161} INFO - Started process (PID=454) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:22:11.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:22:11.609+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:22:11.436+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:22:13.049+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:22:13.001+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:22:13.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:22:14.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 3.544 seconds
[2024-04-17T00:22:46.619+0000] {processor.py:161} INFO - Started process (PID=464) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:22:46.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:22:46.767+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:22:46.767+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:22:48.409+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:22:48.265+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:22:48.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:22:48.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 2.038 seconds
[2024-04-17T00:23:18.978+0000] {processor.py:161} INFO - Started process (PID=475) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:23:18.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:23:18.987+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:18.986+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:23:19.074+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:19.044+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:23:19.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:23:22.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 3.958 seconds
[2024-04-17T00:23:53.236+0000] {processor.py:161} INFO - Started process (PID=492) to work on /opt/airflow/dags/P1.py
[2024-04-17T00:23:53.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/P1.py for tasks to queue
[2024-04-17T00:23:53.246+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:53.240+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/P1.py
[2024-04-17T00:23:53.304+0000] {logging_mixin.py:188} INFO - [2024-04-17T00:23:53.281+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/P1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/P1.py", line 16, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-17T00:23:53.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/P1.py
[2024-04-17T00:23:53.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/P1.py took 0.151 seconds
