[2024-04-06T23:00:47.596+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_clima.ejecutar_mi_script_task manual__2024-04-06T23:00:07.639074+00:00 [queued]>
[2024-04-06T23:00:47.662+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_clima.ejecutar_mi_script_task manual__2024-04-06T23:00:07.639074+00:00 [queued]>
[2024-04-06T23:00:47.679+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-06T23:00:47.775+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): ejecutar_mi_script_task> on 2024-04-06 23:00:07.639074+00:00
[2024-04-06T23:00:47.851+0000] {standard_task_runner.py:60} INFO - Started process 468 to run task
[2024-04-06T23:00:47.865+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_clima', 'ejecutar_mi_script_task', 'manual__2024-04-06T23:00:07.639074+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/Dag_clima.py', '--cfg-path', '/tmp/tmptkl_3ppr']
[2024-04-06T23:00:47.898+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask ejecutar_mi_script_task
[2024-04-06T23:00:48.084+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_clima.ejecutar_mi_script_task manual__2024-04-06T23:00:07.639074+00:00 [running]> on host 0ebc2d070f55
[2024-04-06T23:00:55.777+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_clima' AIRFLOW_CTX_TASK_ID='ejecutar_mi_script_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-06T23:00:07.639074+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-06T23:00:07.639074+00:00'
[2024-04-06T23:00:55.781+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-06T23:00:55.782+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python C:\\Users\\gusta\\Desktop\\Data Engineer\\Semana 7 - Dataframes con SQLalchemy y Psycopg\\TP Entregable\\Script.py']
[2024-04-06T23:00:55.947+0000] {subprocess.py:86} INFO - Output:
[2024-04-06T23:00:56.241+0000] {subprocess.py:93} INFO - python: can't open file 'C:UsersgustaDesktopData': [Errno 2] No such file or directory
[2024-04-06T23:00:56.270+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-06T23:00:56.328+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-06T23:00:56.356+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_clima, task_id=ejecutar_mi_script_task, execution_date=20240406T230007, start_date=20240406T230047, end_date=20240406T230056
[2024-04-06T23:00:56.592+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task ejecutar_mi_script_task (Bash command failed. The command returned a non-zero exit code 2.; 468)
[2024-04-06T23:00:56.643+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-06T23:00:56.721+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
