[2024-04-15T23:32:33.265+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:32:33.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:32:33.550+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:32:33.466+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:32:34.461+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:32:34.465+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:32:35.182+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut7' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:32:39.740+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:32:39.725+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:32:40.664+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:32:40.547+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut7 to 2024-04-14 00:00:00+00:00, run_after=2024-04-15 00:00:00+00:00
[2024-04-15T23:32:41.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 8.104 seconds
[2024-04-15T23:33:11.751+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:33:11.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:33:11.768+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:33:11.767+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:33:11.836+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:33:11.881+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:33:11.952+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut7' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:33:12.155+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:33:12.152+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:33:12.370+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:33:12.369+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut7 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:33:12.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.959 seconds
[2024-04-15T23:33:42.911+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:33:42.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:33:42.920+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:33:42.919+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:33:42.982+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:33:42.983+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:33:43.014+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut7' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:33:43.140+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:33:43.139+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:33:43.244+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:33:43.244+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut7 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:33:43.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.644 seconds
[2024-04-15T23:34:14.218+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:34:14.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:34:14.223+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:34:14.222+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:34:14.257+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:34:14.258+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:34:14.273+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut7' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:34:14.327+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:34:14.326+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:34:14.374+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:34:14.374+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut7 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:34:14.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.382 seconds
[2024-04-15T23:34:44.886+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:34:44.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:34:44.892+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:34:44.892+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:34:44.929+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:34:44.930+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:34:44.949+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut7' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:34:45.020+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:34:45.020+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:34:45.121+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:34:45.121+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut7 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:34:45.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.569 seconds
[2024-04-15T23:35:16.140+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:35:16.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:35:16.154+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:35:16.144+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:35:16.218+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:35:16.219+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:35:16.246+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut7' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:35:16.319+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:35:16.319+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:35:17.181+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:35:17.181+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut7 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:35:17.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.130 seconds
[2024-04-15T23:35:48.585+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:35:48.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:35:48.614+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:35:48.613+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:35:48.664+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:35:48.665+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:35:48.693+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut7' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:35:48.978+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:35:48.978+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:35:49.082+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:35:49.081+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut7 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:35:50.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 1.894 seconds
[2024-04-15T23:36:21.314+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:36:21.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:36:21.319+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:36:21.319+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:36:21.343+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:36:21.344+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:36:21.357+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut7' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:36:21.498+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:36:21.498+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:36:21.529+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:36:21.528+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut7 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:36:23.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.527 seconds
[2024-04-15T23:36:32.292+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:36:32.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:36:32.297+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:36:32.296+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:36:32.637+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:36:32.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:36:32.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.376 seconds
[2024-04-15T23:36:52.514+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:36:52.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:36:52.519+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:36:52.519+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:36:53.014+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:36:53.016+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:36:53.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:36:53.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.587 seconds
[2024-04-15T23:37:24.001+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:37:24.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:37:24.011+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:37:24.010+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:37:24.032+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:37:24.033+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:37:24.034+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:37:24.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.077 seconds
[2024-04-15T23:37:54.408+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:37:54.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:37:54.412+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:37:54.412+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:37:54.441+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:37:54.442+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:37:54.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:37:54.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.078 seconds
[2024-04-15T23:37:58.492+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:37:58.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:37:58.496+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:37:58.496+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:37:58.580+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:37:58.584+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:37:58.586+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:37:58.597+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:37:58.621+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:37:58.600+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Prueba.py", line 50, in <module>
    ejecutar_script_task = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-04-15T23:37:58.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:37:58.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.194 seconds
[2024-04-15T23:38:29.116+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:38:29.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:38:29.121+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:38:29.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:38:29.154+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:38:29.155+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:38:29.156+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:38:29.163+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:38:29.202+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:38:29.165+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Prueba.py", line 50, in <module>
    ejecutar_script_task = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-04-15T23:38:29.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:38:29.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.199 seconds
[2024-04-15T23:38:59.876+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:38:59.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:38:59.881+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:38:59.880+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:38:59.920+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:38:59.922+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:38:59.923+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:38:59.934+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:38:59.948+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:38:59.937+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Prueba.py", line 50, in <module>
    ejecutar_script_task = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-04-15T23:38:59.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:39:00.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.165 seconds
[2024-04-15T23:39:30.843+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:39:30.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:39:30.856+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:39:30.852+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:39:30.936+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:39:30.938+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:39:30.941+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:39:30.954+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:39:31.029+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:39:30.967+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Prueba.py", line 50, in <module>
    ejecutar_script_task = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-04-15T23:39:31.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:39:31.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.311 seconds
[2024-04-15T23:40:02.020+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:40:02.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:40:02.025+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:02.024+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:40:02.074+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:40:02.079+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:40:02.081+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:40:02.101+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:40:02.135+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:02.106+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Prueba.py", line 50, in <module>
    ejecutar_script_task = PythonOperator(
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-04-15T23:40:02.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:40:02.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.235 seconds
[2024-04-15T23:40:04.566+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:40:04.568+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:40:04.571+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:04.570+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:40:04.672+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:40:04.674+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:40:04.676+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:40:04.700+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut8' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:40:05.103+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:05.102+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:m_dag_ejecut8
[2024-04-15T23:40:05.130+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:05.129+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:m_dag_ejecut8
[2024-04-15T23:40:05.153+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:05.152+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:m_dag_ejecut8
[2024-04-15T23:40:05.154+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:05.154+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:40:05.184+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:05.183+0000] {dag.py:3118} INFO - Creating ORM DAG for m_dag_ejecut8
[2024-04-15T23:40:05.241+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:05.240+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut8 to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-15T23:40:05.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.942 seconds
[2024-04-15T23:40:38.141+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:40:38.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:40:38.206+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:38.205+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:40:39.278+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:40:39.287+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:40:39.295+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:40:40.993+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut8' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:40:42.092+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:42.092+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:40:42.618+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:40:42.615+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut8 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:40:43.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 5.356 seconds
[2024-04-15T23:41:13.587+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:41:13.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:41:13.591+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:41:13.590+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:41:13.624+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:41:13.624+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:41:13.625+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:41:13.652+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut8' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:41:13.717+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:41:13.717+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:41:13.753+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:41:13.752+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut8 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:41:13.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.207 seconds
[2024-04-15T23:41:45.081+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:41:45.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:41:45.084+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:41:45.084+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:41:45.110+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:41:45.110+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:41:45.111+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:41:45.123+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut8' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:41:45.156+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:41:45.156+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:41:45.204+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:41:45.204+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut8 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:41:47.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.137 seconds
[2024-04-15T23:42:17.375+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:42:17.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:42:17.380+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:42:17.379+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:42:17.416+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:42:17.419+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:42:17.421+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:42:17.462+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut8' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:42:17.510+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:42:17.510+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:42:17.558+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:42:17.558+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut8 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:42:17.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.233 seconds
[2024-04-15T23:42:48.143+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:42:48.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:42:48.147+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:42:48.146+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:42:48.177+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:42:48.178+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:42:48.179+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:42:48.199+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut8' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:42:48.245+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:42:48.244+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:42:48.295+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:42:48.295+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut8 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:42:48.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.360 seconds
[2024-04-15T23:43:18.564+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:43:18.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:43:18.568+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:43:18.567+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:43:18.591+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:43:18.592+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:43:18.592+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:43:18.605+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut8' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:43:18.661+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:43:18.661+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:43:18.707+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:43:18.706+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut8 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:43:19.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.856 seconds
[2024-04-15T23:43:49.842+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:43:49.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:43:49.856+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:43:49.849+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:43:49.923+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:43:49.925+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:43:49.926+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:43:49.959+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut8' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:43:50.020+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:43:50.020+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:43:50.088+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:43:50.087+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut8 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:43:50.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.304 seconds
[2024-04-15T23:44:20.247+0000] {processor.py:161} INFO - Started process (PID=299) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:44:20.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:44:20.252+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:20.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:44:20.275+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:44:20.276+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:44:20.276+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:44:20.289+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut8' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:44:20.328+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:20.327+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:44:20.366+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:20.366+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut8 to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:44:20.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.166 seconds
[2024-04-15T23:44:27.388+0000] {processor.py:161} INFO - Started process (PID=302) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:44:27.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:44:27.391+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:27.391+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:44:27.442+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:44:27.443+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:44:27.444+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:44:27.463+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:44:27.687+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:27.686+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:m_dag_ejecut.
[2024-04-15T23:44:27.708+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:27.707+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:m_dag_ejecut.
[2024-04-15T23:44:27.727+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:27.726+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:m_dag_ejecut.
[2024-04-15T23:44:27.728+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:27.728+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:44:27.755+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:27.755+0000] {dag.py:3118} INFO - Creating ORM DAG for m_dag_ejecut.
[2024-04-15T23:44:27.771+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:27.771+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-07 00:00:00+00:00, run_after=2024-04-08 00:00:00+00:00
[2024-04-15T23:44:27.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.431 seconds
[2024-04-15T23:44:58.539+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:44:58.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:44:58.560+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:58.559+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:44:58.706+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:44:58.710+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:44:58.722+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:44:58.818+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:44:58.982+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:58.981+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:44:59.249+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:44:59.248+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:44:59.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.849 seconds
[2024-04-15T23:45:29.777+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:45:29.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:45:29.783+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:45:29.782+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:45:29.821+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:45:29.822+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:45:29.822+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:45:29.838+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:45:29.874+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:45:29.873+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:45:29.927+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:45:29.927+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:45:29.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.225 seconds
[2024-04-15T23:46:00.657+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:46:00.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:46:00.662+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:46:00.661+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:46:00.708+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:46:00.709+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:46:00.710+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:46:00.727+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:46:00.780+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:46:00.779+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:46:00.845+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:46:00.844+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:46:00.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.259 seconds
[2024-04-15T23:46:31.037+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:46:31.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:46:31.040+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:46:31.040+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:46:31.065+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:46:31.066+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:46:31.066+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:46:31.081+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:46:31.120+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:46:31.120+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:46:31.153+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:46:31.152+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:46:31.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.153 seconds
[2024-04-15T23:47:01.413+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:47:01.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:47:01.417+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:47:01.416+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:47:01.444+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:47:01.445+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:47:01.445+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:47:01.461+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:47:01.506+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:47:01.505+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:47:01.550+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:47:01.549+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:47:01.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.185 seconds
[2024-04-15T23:47:32.268+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:47:32.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:47:32.272+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:47:32.271+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:47:32.305+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:47:32.306+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:47:32.308+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:47:32.328+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:47:32.428+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:47:32.427+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:47:32.550+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:47:32.550+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:47:32.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.462 seconds
[2024-04-15T23:48:03.226+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:48:03.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:48:03.266+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:48:03.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:48:03.488+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:48:03.489+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:48:03.489+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:48:04.299+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:48:04.386+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:48:04.386+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:48:04.587+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:48:04.586+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:48:05.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.015 seconds
[2024-04-15T23:48:35.491+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:48:35.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:48:35.519+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:48:35.513+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:48:35.564+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:48:35.564+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:48:35.565+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:48:36.023+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:48:40.204+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:48:40.203+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:48:40.554+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:48:40.553+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:48:43.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 7.978 seconds
[2024-04-15T23:49:13.870+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:49:13.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:49:13.873+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:49:13.873+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:49:13.900+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:49:13.901+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:49:13.902+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:49:13.914+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:49:13.954+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:49:13.953+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:49:14.000+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:49:13.999+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:49:14.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.351 seconds
[2024-04-15T23:49:44.659+0000] {processor.py:161} INFO - Started process (PID=410) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:49:44.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:49:44.665+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:49:44.664+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:49:44.701+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:49:44.702+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:49:44.702+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:49:44.719+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:49:44.772+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:49:44.771+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:49:44.853+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:49:44.851+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:49:44.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.268 seconds
[2024-04-15T23:50:16.023+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:50:16.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:50:16.066+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:50:16.065+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:50:17.952+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:50:17.992+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:50:18.036+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:50:18.119+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:50:18.313+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:50:18.312+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:50:18.528+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:50:18.527+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:50:18.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.670 seconds
[2024-04-15T23:50:49.249+0000] {processor.py:161} INFO - Started process (PID=431) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:50:49.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:50:49.335+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:50:49.334+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:50:49.465+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:50:49.473+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:50:49.477+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:50:49.554+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:50:49.722+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:50:49.722+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:50:49.958+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:50:49.957+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:50:50.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.832 seconds
[2024-04-15T23:51:20.224+0000] {processor.py:161} INFO - Started process (PID=441) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:51:20.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:51:20.227+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:51:20.227+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:51:20.253+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:51:20.253+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:51:20.254+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:51:20.269+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:51:20.310+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:51:20.310+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:51:20.348+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:51:20.348+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:51:20.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.163 seconds
[2024-04-15T23:51:50.605+0000] {processor.py:161} INFO - Started process (PID=451) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:51:50.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:51:50.610+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:51:50.609+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:51:50.638+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:51:50.639+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:51:50.639+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:51:50.659+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:51:50.702+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:51:50.701+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:51:50.765+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:51:50.763+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:51:50.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.240 seconds
[2024-04-15T23:52:20.917+0000] {processor.py:161} INFO - Started process (PID=461) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:52:20.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:52:20.923+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:52:20.922+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:52:20.991+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:52:20.993+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:52:20.995+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:52:21.037+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:52:21.113+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:52:21.109+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:52:21.197+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:52:21.196+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:52:21.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.409 seconds
[2024-04-15T23:52:51.638+0000] {processor.py:161} INFO - Started process (PID=471) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:52:51.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:52:51.641+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:52:51.640+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:52:51.668+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:52:51.669+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:52:51.669+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:52:51.686+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:52:51.721+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:52:51.720+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:52:51.753+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:52:51.753+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:52:51.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.152 seconds
[2024-04-15T23:53:21.852+0000] {processor.py:161} INFO - Started process (PID=481) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:53:21.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:53:21.856+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:53:21.855+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:53:21.886+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:53:21.887+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:53:21.888+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:53:21.904+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:53:21.942+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:53:21.942+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:53:21.984+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:53:21.983+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:53:22.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.184 seconds
[2024-04-15T23:53:52.873+0000] {processor.py:161} INFO - Started process (PID=491) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:53:52.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:53:52.878+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:53:52.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:53:53.011+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:53:53.012+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:53:53.013+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:53:53.044+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:53:53.112+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:53:53.112+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:53:53.175+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:53:53.173+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:53:53.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.377 seconds
[2024-04-15T23:54:23.461+0000] {processor.py:161} INFO - Started process (PID=503) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:54:23.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:54:23.464+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:54:23.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:54:23.490+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:54:23.491+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:54:23.491+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:54:23.507+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:54:23.544+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:54:23.544+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:54:23.579+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:54:23.578+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:54:23.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.161 seconds
[2024-04-15T23:55:03.351+0000] {processor.py:161} INFO - Started process (PID=512) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:55:03.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:55:05.042+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:55:05.011+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:55:06.732+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:55:06.733+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:55:07.075+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:55:10.768+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:55:29.711+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:55:29.706+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:55:30.258+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:55:30.245+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:55:30.751+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 28.588 seconds
[2024-04-15T23:56:01.739+0000] {processor.py:161} INFO - Started process (PID=529) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:56:01.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:56:01.744+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:56:01.743+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:56:01.774+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:56:01.775+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:56:01.777+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:56:01.789+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:56:01.831+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:56:01.831+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:56:01.870+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:56:01.870+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:56:03.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 2.077 seconds
[2024-04-15T23:56:34.379+0000] {processor.py:161} INFO - Started process (PID=538) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:56:34.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:56:34.383+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:56:34.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:56:34.413+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:56:34.414+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:56:34.415+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:56:34.435+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:56:34.476+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:56:34.475+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:56:34.521+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:56:34.521+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:56:34.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.387 seconds
[2024-04-15T23:57:05.158+0000] {processor.py:161} INFO - Started process (PID=548) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:57:05.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:57:05.164+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:57:05.163+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:57:05.229+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:57:05.232+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:57:05.234+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:57:05.262+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:57:05.361+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:57:05.361+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:57:05.473+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:57:05.472+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:57:05.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.404 seconds
[2024-04-15T23:57:35.869+0000] {processor.py:161} INFO - Started process (PID=559) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:57:35.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:57:35.874+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:57:35.873+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:57:35.927+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:57:35.928+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:57:35.929+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:57:35.957+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:57:36.012+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:57:36.011+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:57:36.065+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:57:36.065+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:57:36.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.286 seconds
[2024-04-15T23:58:06.271+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:58:06.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:58:06.275+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:58:06.275+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:58:06.310+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:58:06.311+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:58:06.312+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:58:06.328+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:58:06.370+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:58:06.370+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:58:06.410+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:58:06.409+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:58:06.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.204 seconds
[2024-04-15T23:58:36.734+0000] {processor.py:161} INFO - Started process (PID=579) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:58:36.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:58:36.739+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:58:36.738+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:58:36.797+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:58:36.798+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:58:36.799+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:58:36.827+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:58:36.890+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:58:36.889+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:58:36.975+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:58:36.974+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:58:37.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.351 seconds
[2024-04-15T23:59:07.655+0000] {processor.py:161} INFO - Started process (PID=589) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:59:07.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:59:07.659+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:59:07.659+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:59:07.696+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:59:07.697+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:59:07.698+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:59:07.721+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:59:07.776+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:59:07.775+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:59:07.836+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:59:07.835+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:59:07.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.241 seconds
[2024-04-15T23:59:38.140+0000] {processor.py:161} INFO - Started process (PID=599) to work on /opt/airflow/dags/Prueba.py
[2024-04-15T23:59:38.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Prueba.py for tasks to queue
[2024-04-15T23:59:38.145+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:59:38.145+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Prueba.py
[2024-04-15T23:59:38.181+0000] {logging_mixin.py:188} INFO - /opt/Prueba2.py
[2024-04-15T23:59:38.183+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:59:38.184+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:59:38.202+0000] {processor.py:840} INFO - DAG(s) 'm_dag_ejecut.' retrieved from /opt/airflow/dags/Prueba.py
[2024-04-15T23:59:38.256+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:59:38.255+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-15T23:59:38.312+0000] {logging_mixin.py:188} INFO - [2024-04-15T23:59:38.311+0000] {dag.py:3954} INFO - Setting next_dagrun for m_dag_ejecut. to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-15T23:59:38.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Prueba.py took 0.227 seconds
